services:
  nats-server:
    image: nats:latest

  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: Dockerfile.prod
    image: southamerica-west1-docker.pkg.dev/nest-microservices-430412/image-registry/client-gateway-prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222

  products-ms:
    build:
      context: ./products-ms
      dockerfile: Dockerfile.prod
    image: southamerica-west1-docker.pkg.dev/nest-microservices-430412/image-registry/products-ms-prod
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db

  payments-ms:
    build:
      context: ./payments-ms
      dockerfile: Dockerfile.prod
    image: southamerica-west1-docker.pkg.dev/nest-microservices-430412/image-registry/payments-ms-prod
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=${PAYMENTS_MS_NATS_SERVERS}
      - STRIPE_SECRET=${PAYMENTS_MS_STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${PAYMENTS_MS_STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${PAYMENTS_MS_STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${PAYMENTS_MS_STRIPE_ENDPOINT_SECRET}

  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: Dockerfile.prod
    image: southamerica-west1-docker.pkg.dev/nest-microservices-430412/image-registry/auth-ms-prod
    environment:
      - PORT=3004
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

  orders-ms:
    build:
      context: ./orders-ms
      dockerfile: Dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: southamerica-west1-docker.pkg.dev/nest-microservices-430412/image-registry/orders-ms-prod
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_DATABASE_URL}
